### ISSUE TITLE
Solution Will not Build

### ISSUE THREAD

**Issue by SailingNut** [tkhadimullin/trex-exporter#1]
I cloned the repo, opened the solution in VS 2022 and built the solution.

Here are the errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'key'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	27	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'value'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	27	N/A
Error	CS0117	'Session' does not contain a definition for 'GetMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	27	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'key'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	28	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'value'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	28	N/A
Error	CS0117	'GPU' does not contain a definition for 'GetMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	28	N/A
Error	CS0117	'Session' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	33	N/A
Error	CS0117	'GPU' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\LolMinerPoller.cs	37	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'key'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	18	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'value'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	18	N/A
Error	CS0117	'TRexResponse' does not contain a definition for 'GetMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	18	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'key'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	19	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'value'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	19	N/A
Error	CS0117	'DualStat' does not contain a definition for 'GetMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	19	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'key'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	20	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'value'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	20	N/A
Error	CS0117	'Gpu' does not contain a definition for 'GetMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	20	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'key'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	21	N/A
Error	CS8130	Cannot infer the type of implicitly-typed deconstruction variable 'value'.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	21	N/A
Error	CS0117	'Shares' does not contain a definition for 'GetMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	21	N/A
Error	CS0117	'TRexResponse' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	25	N/A
Error	CS0117	'Gpu' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	29	N/A
Error	CS0117	'Shares' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	35	N/A
Error	CS0117	'DualStat' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	44	N/A
Error	CS0117	'Gpu' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	46	N/A
Error	CS0117	'Shares' does not contain a definition for 'UpdateMetrics'	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\TRexPoller.cs	52	N/A
Warning	CS8032	An instance of analyzer MetricsGenerator.MetricsGenerator cannot be created from C:\Users\tim\source\repos\trex-exporter\MetricsGenerator\bin\Debug\netstandard2.0\MetricsGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\CSC	1	N/A
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	TrexExporter	C:\Users\tim\source\repos\trex-exporter\TRexExporter\PrometheusExporter.cs	20	N/A

**Comment by tkhadimullin** [comment]
Appears your source code generator did not run. Can you double check that [MetricsGenerator](https://github.com/tkhadimullin/trex-exporter/tree/master/MetricsGenerator) project has built successfully and restart visual studio?

**Comment by SailingNut** [comment]
I did a rebuild on the MetricsGenerator project and that worked without issue. I then restarted VS and did a rebuild on the TrexExporter and I still get the same errors.

**Comment by SailingNut** [comment]
After looking deeper into this it appears that the MetricsGenerator.dll cannot be loaded because it is unable to find the Microsoft.CodeAnalysis Version=4.1.0

It seems to be an environmental issue, but I've done a ton of Googling and have not found a solution that works.

I am using Visual Studio 2022

**Comment by tkhadimullin** [comment]
I have just started off with git clean state and am also using VS2022. I noticed that the package in question has indeed been long cached on my machine. But the solution kept building even after i cleaned that cache too (I first build the generator and then restart VS so it gets a chance to pick up the analyser).

At this stage, the only thing I could suggest would be to 
1. double check you have correct NuGet.org source feeds set up, and 
2. try upgrading both `Microsoft.CodeAnalysis` and  `Microsoft.CodeAnalysis.CSharp` to the latest stable `4.2.0`. 

Hopefully, that gets you unstuck.

```xml
<PackageReference Include="Microsoft.CodeAnalysis" Version="4.2.0" />
...
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.2.0" />
```

**Comment by SailingNut** [comment]
Thanks for the info. I tried that and now it complains about not being able to load Microsoft.CodeAnalysis Version=4.2.0

Here's what I did:

1. Update Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.CSharp to the latest stable 4.2.0.
2. Rebuild MetricsGenerator
3. Rebuild TrexExporter
4. Fail
5. Restart VS
6. Rebuild TrexExporter
7. Fail

**Comment by tkhadimullin** [comment]
have you tried using `dotnet cli` or VS Code to build it?
Can you try pulling the latest and opening it in VSCode? It should then pick up on dev container config and guide you through the process. 

If you don't have docker, it should still work in VS, you may need to use dotnet cli manually and first build generators followed by main exporters

**Comment by SailingNut** [comment]
Building with "dotnet build" worked. Now just struggling to find where to set the port on which trex is exposing it's API as well as how to set the API username and password.
